# Generated by Django 4.2.7 on 2025-12-09 12:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Warehouse', '0005_alter_warehousevision_vision_and_more'),
        ('Shipments', '0004_alter_shipment_unit'),
        ('Unit', '0001_initial'),
        ('Forklift', '0003_alter_unload_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unload',
            name='license_number',
        ),
        migrations.AddField(
            model_name='unload',
            name='shipment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='Shipments.shipment'),
        ),
        migrations.AddField(
            model_name='unload',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='Unit.unit'),
        ),
        migrations.AlterField(
            model_name='unload',
            name='unload_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='Warehouse.warehouse'),
        ),
    ]
