# Generated by Django 4.2.7 on 2026-05-03 06:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Forklift', '0001_initial'),
        ('Shipments', '0001_initial'),
        ('Warehouse', '0001_initial'),
        ('Unit', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='unload',
            name='shipment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='Shipments.shipment'),
        ),
        migrations.AddField(
            model_name='unload',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='Unit.unit'),
        ),
        migrations.AddField(
            model_name='unload',
            name='unload_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='Warehouse.warehouse'),
        ),
    ]
