# Generated by Django 5.2.5 on 2025-12-28 07:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PLC_Monitoring', '0008_rolls_remove_plc_logs_roll_number_roll_breaks_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rolls',
            name='plc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rolls', to='PLC_Monitoring.plc'),
        ),
    ]
