# Generated by Django 4.2.7 on 2026-06-20 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='versioncontrol',
            name='desc',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='versioncontrol',
            name='CreationDateTime',
            field=models.CharField(blank=True, default=1781938494.5613725, max_length=50, null=True, verbose_name='زمان ساخت'),
        ),
    ]
