# Generated by Django 4.2.7 on 2026-05-26 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PLC_Monitoring', '0015_alter_keyalertconfig_color_max_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TCP_CONNECTION',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('LastUpdate', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
    ]
