# Generated by Django 4.2.7 on 2026-06-10 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_versioncontrol_creationdatetime'),
    ]

    operations = [
        migrations.CreateModel(
            name='TCP_CONNECTION',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ServerLastUpdate', models.FloatField(blank=True, null=True)),
                ('ClientLastUpdate', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='versioncontrol',
            name='CreationDateTime',
            field=models.CharField(blank=True, default=1781090319.634872, max_length=50, null=True, verbose_name='زمان ساخت'),
        ),
    ]
