# Generated by Django 4.2.7 on 2026-06-15 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_tcp_connection_alter_versioncontrol_creationdatetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='versioncontrol',
            name='desc',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='versioncontrol',
            name='CreationDateTime',
            field=models.CharField(blank=True, default=1781524641.0198684, max_length=50, null=True, verbose_name='زمان ساخت'),
        ),
    ]
