# Generated by Django 4.2.7 on 2025-11-25 09:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Visions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vision',
            name='vision_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='VisionData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField(blank=True, null=True)),
                ('CreationDateTime', models.FloatField(blank=True, max_length=50, null=True, verbose_name='زمان ساخت')),
                ('LastUpdate', models.FloatField(blank=True, max_length=50, null=True, verbose_name='آخرین آپدیت')),
                ('vision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vision_data', to='Visions.vision', verbose_name='ویژن')),
            ],
        ),
    ]
