# Generated by Django 4.2.7 on 2025-12-03 13:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Warehouse', '0005_alter_warehousevision_vision_and_more'),
        ('Visions', '0004_visiondata_detections_time_visiondata_enter_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vision',
            name='warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vision_warehouse', to='Warehouse.warehouse', verbose_name='انبار'),
        ),
    ]
