# Generated by Django 4.2.7 on 2026-05-03 06:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ProductsMachine', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductsType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='نام نوع کاغذ')),
                ('description', models.TextField(blank=True, null=True)),
                ('CreationDateTime', models.DateTimeField(auto_now_add=True, db_index=True, null=True)),
                ('LastUpdate', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll_number', models.CharField(max_length=255)),
                ('production_details', models.JSONField(blank=True, null=True)),
                ('width', models.FloatField(blank=True, null=True)),
                ('grammage', models.FloatField(blank=True, null=True)),
                ('length', models.FloatField(blank=True, null=True)),
                ('breaks', models.IntegerField(blank=True, null=True)),
                ('profile', models.IntegerField(choices=[(1, '0'), (2, '200'), (3, '210-220'), (4, '240-250')], default=2)),
                ('qr', models.CharField(blank=True, max_length=100, null=True)),
                ('excluded_fields_in_qr', models.CharField(blank=True, max_length=200, null=True)),
                ('custome_qr', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('Is_Deleted', models.BooleanField(default=False)),
                ('CreationTimestamp', models.FloatField(blank=True, null=True)),
                ('CreationDateTime', models.DateTimeField(auto_now_add=True, db_index=True, null=True)),
                ('LastUpdate', models.DateTimeField(auto_now=True, null=True)),
                ('products_machine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ProductsMachine', to='ProductsMachine.productsmachine', verbose_name='ماشین تولید')),
                ('type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ProductsType', to='Products.productstype', verbose_name='نوع محصول')),
            ],
        ),
    ]
