# Generated by Django 4.2.7 on 2026-05-06 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QR_Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('excluded_fields_in_qr', models.CharField(blank=True, max_length=200, null=True)),
                ('custome_qr', models.TextField(blank=True, null=True)),
                ('CreationTimestamp', models.FloatField(blank=True, null=True)),
                ('CreationDateTime', models.DateTimeField(auto_now_add=True, db_index=True, null=True)),
                ('LastUpdate', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='products',
            name='custome_qr',
        ),
        migrations.RemoveField(
            model_name='products',
            name='excluded_fields_in_qr',
        ),
    ]
