# Generated by Django 4.2.7 on 2026-05-24 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PLC_Monitoring', '0014_plc_keys_live_background_value_max_keyalertconfig_min_max_2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keyalertconfig',
            name='color_max',
            field=models.CharField(blank=True, default='#ff8800', max_length=20),
        ),
        migrations.AlterField(
            model_name='keyalertconfig',
            name='color_max_2',
            field=models.CharField(blank=True, default='#ff4444', max_length=20),
        ),
        migrations.AlterField(
            model_name='keyalertconfig',
            name='color_min_2',
            field=models.CharField(blank=True, default='#ff8800', max_length=20),
        ),
    ]
