# Generated by Django 4.2.7 on 2025-08-31 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_versioncontrol_creationdatetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='versioncontrol',
            name='CreationDateTime',
            field=models.CharField(blank=True, default=1756625408.2011588, max_length=50, null=True, verbose_name='زمان ساخت'),
        ),
    ]
