# Generated by Django 4.2.7 on 2026-05-24 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_versioncontrol_creationdatetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='versioncontrol',
            name='desc',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='versioncontrol',
            name='CreationDateTime',
            field=models.CharField(blank=True, default=1779605566.3656685, max_length=50, null=True, verbose_name='زمان ساخت'),
        ),
    ]
