# Generated by Django 4.2.7 on 2026-07-13 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_versioncontrol_desc_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='versioncontrol',
            name='CreationDateTime',
            field=models.CharField(blank=True, default=1783922190.6094027, max_length=50, null=True, verbose_name='زمان ساخت'),
        ),
    ]
