# Generated by Django 4.2.7 on 2025-11-29 09:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Warehouse', '0005_alter_warehousevision_vision_and_more'),
        ('Visions', '0002_vision_vision_id_visiondata'),
    ]

    operations = [
        migrations.AddField(
            model_name='vision',
            name='warehouse',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='vision_warehouse', to='Warehouse.warehouse', verbose_name='انبار'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='visiondata',
            name='count',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='visiondata',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
