# Generated by Django 4.2.7 on 2026-01-06 12:54

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChartExcludedKeys',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(db_index=True, max_length=100, unique=True)),
                ('CreationDateTime', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='زمان ساخت')),
            ],
        ),
        migrations.CreateModel(
            name='PLC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(db_index=True, max_length=50, unique=True)),
                ('ip_address', models.CharField(blank=True, max_length=100, null=True)),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('setting', models.JSONField(blank=True, null=True)),
                ('Is_Known', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True, null=True)),
                ('CreationDateTime', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='زمان ساخت')),
                ('LastUpdate', models.DateTimeField(auto_now_add=True, verbose_name='آخرین آپدیت')),
            ],
        ),
        migrations.CreateModel(
            name='PLC_Keys',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('fa_name', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('key', models.CharField(db_index=True, max_length=100)),
                ('value', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('order_index', models.IntegerField(db_index=True, default=0)),
                ('description', models.TextField(blank=True, null=True)),
                ('CreationDateTime', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='زمان ساخت')),
                ('LastUpdate', models.DateTimeField(auto_now_add=True, verbose_name='آخرین آپدیت')),
            ],
        ),
        migrations.CreateModel(
            name='Rolls',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plc_setting', models.JSONField(blank=True, null=True)),
                ('roll_number', models.IntegerField(blank=True, db_index=True, null=True)),
                ('Printed_length', models.IntegerField(blank=True, default=0, null=True)),
                ('Paper_breaks', models.IntegerField(blank=True, default=0, null=True)),
                ('Is_Deleted', models.BooleanField(blank=True, default=False, null=True)),
                ('CreationDateTime', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='زمان ساخت')),
                ('LastUpdate', models.DateTimeField(auto_now_add=True, verbose_name='آخرین آپدیت')),
                ('plc', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rolls', to='PLC_Monitoring.plc')),
            ],
        ),
        migrations.CreateModel(
            name='Roll_Breaks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('break_reason', models.CharField(blank=True, max_length=250, null=True)),
                ('CreationDateTime', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='زمان ساخت')),
                ('LastUpdate', models.DateTimeField(auto_now_add=True, verbose_name='آخرین آپدیت')),
                ('roll', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='roll_breaks', to='PLC_Monitoring.rolls')),
            ],
        ),
        migrations.CreateModel(
            name='PLC_Logs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_running', models.BooleanField(blank=True, default=False, null=True)),
                ('data', models.TextField()),
                ('json_data', models.JSONField(blank=True, null=True)),
                ('CreationDateTime', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='زمان ساخت')),
                ('LastUpdate', models.DateTimeField(auto_now_add=True, verbose_name='آخرین آپدیت')),
                ('plc', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='plc_logs', to='PLC_Monitoring.plc')),
                ('roll', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='roll_logs', to='PLC_Monitoring.rolls')),
            ],
        ),
        migrations.AddIndex(
            model_name='plc',
            index=models.Index(fields=['device_id'], name='PLC_Monitor_device__32d612_idx'),
        ),
        migrations.AddIndex(
            model_name='plc',
            index=models.Index(fields=['CreationDateTime'], name='PLC_Monitor_Creatio_df5b33_idx'),
        ),
    ]
