# Generated by Django 4.2.7 on 2025-09-09 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('save_logs', '0002_alter_device_creationdatetime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='CreationDateTime',
            field=models.CharField(blank=True, default=1757405936.741241, max_length=50, null=True, verbose_name='زمان ساخت'),
        ),
        migrations.AlterField(
            model_name='device_sensor',
            name='CreationDateTime',
            field=models.CharField(blank=True, default=1757405936.741241, max_length=50, null=True, verbose_name='زمان ساخت'),
        ),
        migrations.AlterField(
            model_name='sensorlogs',
            name='CreationDateTime',
            field=models.CharField(blank=True, default=1757405936.741241, max_length=50, null=True, verbose_name='زمان ساخت'),
        ),
    ]
