# Generated by Django 4.2.7 on 2025-08-31 07:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(max_length=50, unique=True)),
                ('ip_address', models.CharField(blank=True, max_length=100, null=True)),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('Is_Known', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True, null=True)),
                ('CreationDateTime', models.CharField(blank=True, default=1756625437.3945892, max_length=50, null=True, verbose_name='زمان ساخت')),
                ('LastUpdate', models.CharField(blank=True, max_length=50, null=True, verbose_name='آخرین آپدیت')),
            ],
        ),
        migrations.CreateModel(
            name='Device_Sensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sensor_type', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('CreationDateTime', models.CharField(blank=True, default=1756625437.3945892, max_length=50, null=True, verbose_name='زمان ساخت')),
                ('LastUpdate', models.CharField(blank=True, max_length=50, null=True, verbose_name='آخرین آپدیت')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='save_logs.device')),
            ],
        ),
        migrations.CreateModel(
            name='SensorLogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.TextField()),
                ('CreationDateTime', models.CharField(blank=True, default=1756625437.3945892, max_length=50, null=True, verbose_name='زمان ساخت')),
                ('LastUpdate', models.CharField(blank=True, max_length=50, null=True, verbose_name='آخرین آپدیت')),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='save_logs.device_sensor')),
            ],
        ),
    ]
