# Generated by Django 4.2.7 on 2025-11-29 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='نام')),
                ('phone', models.CharField(blank=True, max_length=255, null=True, verbose_name='شماره تلفن')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='آدرس')),
                ('email', models.EmailField(blank=True, max_length=255, null=True, verbose_name='ایمیل')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('Is_Deleted', models.BooleanField(default=False)),
                ('CreationDateTime', models.FloatField(blank=True, max_length=50, null=True, verbose_name='زمان ساخت')),
                ('LastUpdate', models.FloatField(blank=True, max_length=50, null=True, verbose_name='آخرین آپدیت')),
            ],
            options={
                'verbose_name': 'تامین کننده',
                'verbose_name_plural': 'تامین کنندگان',
            },
        ),
    ]
