# Generated by Django 4.2.7 on 2025-12-13 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('save_logs', '0005_device_ai_target_device_is_ai_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='CreationDateTime',
            field=models.FloatField(blank=True, db_index=True, max_length=50, null=True, verbose_name='زمان ساخت'),
        ),
        migrations.AlterField(
            model_name='device',
            name='device_id',
            field=models.CharField(db_index=True, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='device_sensor',
            name='CreationDateTime',
            field=models.FloatField(blank=True, db_index=True, max_length=50, null=True, verbose_name='زمان ساخت'),
        ),
        migrations.AlterField(
            model_name='device_sensor',
            name='sensor_type',
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='sensorlogs',
            name='CreationDateTime',
            field=models.FloatField(blank=True, db_index=True, null=True, verbose_name='زمان ساخت'),
        ),
        migrations.AddIndex(
            model_name='device',
            index=models.Index(fields=['device_id'], name='save_logs_d_device__2388a1_idx'),
        ),
        migrations.AddIndex(
            model_name='device',
            index=models.Index(fields=['CreationDateTime'], name='save_logs_d_Creatio_244636_idx'),
        ),
        migrations.AddIndex(
            model_name='device_sensor',
            index=models.Index(fields=['device', 'sensor_type'], name='save_logs_d_device__0108d1_idx'),
        ),
        migrations.AddIndex(
            model_name='device_sensor',
            index=models.Index(fields=['CreationDateTime'], name='save_logs_d_Creatio_9ef201_idx'),
        ),
        migrations.AddIndex(
            model_name='sensorlogs',
            index=models.Index(fields=['sensor', 'CreationDateTime'], name='save_logs_s_sensor__2e2381_idx'),
        ),
        migrations.AddIndex(
            model_name='sensorlogs',
            index=models.Index(fields=['-CreationDateTime'], name='save_logs_s_Creatio_a3c7ca_idx'),
        ),
    ]
