# Generated by Django 4.2.7 on 2026-03-01 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_versioncontrol_creationdatetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='versioncontrol',
            name='CreationDateTime',
            field=models.CharField(blank=True, default=1772353804.3594236, max_length=50, null=True, verbose_name='زمان ساخت'),
        ),
    ]
