# Generated by Django 4.2.7 on 2025-12-13 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_alter_versioncontrol_creationdatetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='versioncontrol',
            name='CreationDateTime',
            field=models.CharField(blank=True, default=1765615621.8567338, max_length=50, null=True, verbose_name='زمان ساخت'),
        ),
    ]
