# Generated by Django 4.2.7 on 2026-07-13 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PLC_Monitoring', '0017_remove_tcp_connection_lastupdate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='plc_keys',
            name='offset',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
