# Generated by Django 4.2.7 on 2025-11-23 11:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Visions', '0001_initial'),
        ('Warehouse', '0003_warehouse_vision'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='warehouse',
            name='vision',
        ),
        migrations.CreateModel(
            name='WarehouseVision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Is_Deleted', models.BooleanField(default=False)),
                ('CreationDateTime', models.FloatField(blank=True, max_length=50, null=True, verbose_name='زمان ساخت')),
                ('LastUpdate', models.FloatField(blank=True, max_length=50, null=True, verbose_name='آخرین آپدیت')),
                ('vision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Visions.vision')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Warehouse.warehouse')),
            ],
        ),
    ]
