# Generated by Django 4.2.7 on 2025-12-03 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Visions', '0003_vision_warehouse_visiondata_count_visiondata_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='visiondata',
            name='detections_time',
            field=models.FloatField(blank=True, max_length=50, null=True, verbose_name='زمان تشخیص'),
        ),
        migrations.AddField(
            model_name='visiondata',
            name='enter',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='ورود'),
        ),
        migrations.AddField(
            model_name='visiondata',
            name='exit',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='خروج'),
        ),
    ]
