# Generated by Django 4.2.7 on 2025-11-22 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Warehouse', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehouse',
            name='Is_Deleted',
            field=models.BooleanField(default=False),
        ),
    ]
