# Generated by Django 4.2.7 on 2025-11-26 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Forklift', '0002_forklift_drivers_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unload',
            name='quantity',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
