# Generated by Django 4.2.7 on 2026-06-10 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PLC_Monitoring', '0013_alter_chartexcludedkeys_creationdatetime_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TCP_CONNECTION',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ServerLastUpdate', models.FloatField(blank=True, null=True)),
                ('ClientLastUpdate', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
