# Generated by Django 4.2.7 on 2026-06-15 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PLC_Monitoring', '0014_tcp_connection'),
    ]

    operations = [
        migrations.AddField(
            model_name='keyalertconfig',
            name='color_max_2',
            field=models.CharField(blank=True, default='#ff4444', max_length=20),
        ),
        migrations.AddField(
            model_name='keyalertconfig',
            name='color_min_2',
            field=models.CharField(blank=True, default='#ffaa00', max_length=20),
        ),
        migrations.AddField(
            model_name='keyalertconfig',
            name='max_value_2',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='keyalertconfig',
            name='min_value_2',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='plc_keys',
            name='live_background',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='plc_keys',
            name='value_max',
            field=models.FloatField(blank=True, default=100),
        ),
        migrations.AlterField(
            model_name='keyalertconfig',
            name='CreationDateTime',
            field=models.DateTimeField(auto_now_add=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='keyalertconfig',
            name='LastUpdate',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='keyalertconfig',
            name='color_max',
            field=models.CharField(blank=True, default='#ff8800', max_length=20),
        ),
        migrations.AlterField(
            model_name='keyalertconfig',
            name='color_min',
            field=models.CharField(blank=True, default='#ff4444', max_length=20),
        ),
    ]
