# Generated by Django 4.2.7 on 2026-07-16 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PLC_Monitoring', '0015_keyalertconfig_color_max_2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plc',
            name='LastUpdate',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='آخرین آپدیت'),
        ),
    ]
