# Generated by Django 4.2.7 on 2026-07-16 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PLC_Monitoring', '0002_tcp_connection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plc_logs',
            name='LastUpdate',
            field=models.DateTimeField(auto_now=True, db_index=True, null=True),
        ),
    ]
