# Generated by Django 4.2.7 on 2025-12-08 06:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Warehouse', '0005_alter_warehousevision_vision_and_more'),
        ('Visions', '0006_organizingvisiondata'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizingvisiondata',
            name='class_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='نام'),
        ),
        migrations.AddField(
            model_name='organizingvisiondata',
            name='vision',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='organizing_vision_data', to='Visions.vision', verbose_name='ویژن'),
        ),
        migrations.AlterField(
            model_name='organizingvisiondata',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='Warehouse.warehouse', verbose_name='انبار'),
        ),
    ]
