# Generated by Django 4.2.7 on 2025-12-08 06:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Forklift', '0003_alter_unload_quantity'),
        ('Visions', '0007_organizingvisiondata_class_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizingvisiondata',
            name='forklift_driver_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='Forklift.forklift_drivers', verbose_name='نام راننده'),
        ),
    ]
