# Generated by Django 4.2.7 on 2025-12-08 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Visions', '0011_organizingvisiondata_time_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizingvisiondata',
            name='time',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='زمان'),
        ),
    ]
