# Generated by Django 4.2.7 on 2025-12-10 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Visions', '0014_organizingvisiondata_destenation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizingvisiondata',
            name='Is_Checked',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='بررسی شده'),
        ),
    ]
