# Generated by Django 4.2.7 on 2025-09-17 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_alter_versioncontrol_creationdatetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='versioncontrol',
            name='CreationDateTime',
            field=models.CharField(blank=True, default=1758105227.1104493, max_length=50, null=True, verbose_name='زمان ساخت'),
        ),
    ]
