# Generated by Django 4.2.7 on 2025-11-26 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Forklift', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='forklift_drivers',
            name='phone',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
