# Generated by Django 4.2.7 on 2025-12-16 06:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PLC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(db_index=True, max_length=50, unique=True)),
                ('ip_address', models.CharField(blank=True, max_length=100, null=True)),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('Is_Known', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True, null=True)),
                ('CreationDateTime', models.FloatField(blank=True, db_index=True, max_length=50, null=True, verbose_name='زمان ساخت')),
                ('LastUpdate', models.FloatField(blank=True, max_length=50, null=True, verbose_name='آخرین آپدیت')),
            ],
        ),
        migrations.CreateModel(
            name='PLC_Logs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.TextField()),
                ('CreationDateTime', models.FloatField(blank=True, db_index=True, null=True, verbose_name='زمان ساخت')),
                ('LastUpdate', models.FloatField(blank=True, max_length=50, null=True, verbose_name='آخرین آپدیت')),
                ('plc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plc_logs', to='PLC_Monitoring.plc')),
            ],
        ),
        migrations.AddIndex(
            model_name='plc',
            index=models.Index(fields=['device_id'], name='PLC_Monitor_device__32d612_idx'),
        ),
        migrations.AddIndex(
            model_name='plc',
            index=models.Index(fields=['CreationDateTime'], name='PLC_Monitor_Creatio_df5b33_idx'),
        ),
    ]
