# Generated by Django 4.2.7

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PLC_Monitoring', '0014_plc_keys_live_background_value_max_keyalertconfig_min_max_2'),
    ]

    operations = [
        migrations.CreateModel(
            name='LiveSettingsGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=150)),
            ],
            options={
                'verbose_name': 'گروه نمایش زنده',
                'verbose_name_plural': 'گروه\u200cهای نمایش زنده',
            },
        ),
        migrations.AddField(
            model_name='plc_keys',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='keys', to='PLC_Monitoring.livesettingsgroup', db_index=True),
        ),
        migrations.AddField(
            model_name='plc_keys',
            name='order_in_group',
            field=models.IntegerField(db_index=True, default=0),
        ),
    ]
