# Generated by Django 4.2.7 on 2026-03-01 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PLC_Monitoring', '0015_livesettingsgroup_plc_keys_group_order_in_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='livesettingsgroup',
            name='order',
            field=models.IntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='keyalertconfig',
            name='color_max',
            field=models.CharField(blank=True, default='#ff8800', max_length=20),
        ),
        migrations.AlterField(
            model_name='keyalertconfig',
            name='color_max_2',
            field=models.CharField(blank=True, default='#ff4444', max_length=20),
        ),
        migrations.AlterField(
            model_name='keyalertconfig',
            name='color_min_2',
            field=models.CharField(blank=True, default='#ff8800', max_length=20),
        ),
    ]
