# Generated by Django 4.2.7 on 2025-11-26 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Material', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialtype',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
