# Generated by Django 4.2.7 on 2025-11-26 09:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Warehouse', '0004_remove_warehouse_vision_warehousevision'),
        ('Trucks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Forklift_Drivers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('Is_Deleted', models.BooleanField(default=False)),
                ('CreationDateTime', models.FloatField(blank=True, max_length=50, null=True, verbose_name='زمان ساخت')),
                ('LastUpdate', models.FloatField(blank=True, max_length=50, null=True, verbose_name='آخرین آپدیت')),
            ],
        ),
        migrations.CreateModel(
            name='Unload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('quality', models.CharField(blank=True, max_length=255, null=True)),
                ('Is_Deleted', models.BooleanField(default=False)),
                ('CreationDateTime', models.FloatField(blank=True, max_length=50, null=True, verbose_name='زمان ساخت')),
                ('LastUpdate', models.FloatField(blank=True, max_length=50, null=True, verbose_name='آخرین آپدیت')),
                ('forklift_driver_name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Forklift.forklift_drivers')),
                ('license_number', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Trucks.truck')),
                ('unload_location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Warehouse.warehouse')),
            ],
        ),
    ]
