# Generated by Django 4.2.7 on 2025-12-17 14:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PLC_Monitoring', '0002_plc_keys'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plc_logs',
            name='plc',
        ),
        migrations.AlterField(
            model_name='plc_keys',
            name='plc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='plc_keys', to='PLC_Monitoring.plc'),
        ),
    ]
