# Generated by Django 5.2.5 on 2025-12-22 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PLC_Monitoring', '0005_plc_setting_plc_keys_description_plc_keys_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='plc_keys',
            name='fa_name',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
    ]
