# Generated by Django 4.2.7 on 2025-11-26 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Truck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('License_plate_number', models.CharField(max_length=16)),
                ('Truck_type', models.CharField(blank=True, max_length=255, null=True)),
                ('Truck_color', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('Free', 'Free'), ('Busy', 'Busy')], default='Free', max_length=10)),
                ('location', models.CharField(blank=True, default='Entrance', max_length=255)),
                ('driver_name', models.CharField(blank=True, max_length=255, null=True)),
                ('driver_doc', models.CharField(blank=True, max_length=255, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('Is_Deleted', models.BooleanField(default=False)),
                ('CreationDateTime', models.FloatField(blank=True, max_length=50, null=True, verbose_name='زمان ساخت')),
                ('LastUpdate', models.FloatField(blank=True, max_length=50, null=True, verbose_name='آخرین آپدیت')),
            ],
        ),
    ]
