# Generated by Django 4.2.7 on 2025-11-29 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='versioncontrol',
            name='CreationDateTime',
            field=models.CharField(blank=True, default=1764418874.7065337, max_length=50, null=True, verbose_name='زمان ساخت'),
        ),
    ]
