# Generated by Django 4.2.7 on 2025-09-17 10:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('save_logs', '0003_alter_device_creationdatetime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='CreationDateTime',
            field=models.FloatField(blank=True, max_length=50, null=True, verbose_name='زمان ساخت'),
        ),
        migrations.AlterField(
            model_name='device',
            name='LastUpdate',
            field=models.FloatField(blank=True, max_length=50, null=True, verbose_name='آخرین آپدیت'),
        ),
        migrations.AlterField(
            model_name='device_sensor',
            name='CreationDateTime',
            field=models.FloatField(blank=True, max_length=50, null=True, verbose_name='زمان ساخت'),
        ),
        migrations.AlterField(
            model_name='device_sensor',
            name='LastUpdate',
            field=models.FloatField(blank=True, max_length=50, null=True, verbose_name='آخرین آپدیت'),
        ),
        migrations.AlterField(
            model_name='device_sensor',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sensors', to='save_logs.device'),
        ),
        migrations.AlterField(
            model_name='sensorlogs',
            name='CreationDateTime',
            field=models.FloatField(blank=True, null=True, verbose_name='زمان ساخت'),
        ),
        migrations.AlterField(
            model_name='sensorlogs',
            name='LastUpdate',
            field=models.FloatField(blank=True, max_length=50, null=True, verbose_name='آخرین آپدیت'),
        ),
        migrations.AlterField(
            model_name='sensorlogs',
            name='sensor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sensor_logs', to='save_logs.device_sensor'),
        ),
    ]
