# Generated by Django 5.2.5 on 2025-12-22 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PLC_Monitoring', '0004_remove_plc_keys_plc_plc_logs_json_data_plc_logs_plc'),
    ]

    operations = [
        migrations.AddField(
            model_name='plc',
            name='setting',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='plc_keys',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='plc_keys',
            name='name',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
    ]
