# Generated by Django 5.2.5 on 2025-12-28 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PLC_Monitoring', '0009_rolls_plc'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChartExcludedKeys',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(db_index=True, max_length=100, unique=True)),
                ('CreationDateTime', models.FloatField(blank=True, db_index=True, null=True, verbose_name='زمان ساخت')),
            ],
        ),
    ]
