# Generated by Django 4.2.7 on 2026-01-26 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PLC_Monitoring', '0011_plc_keys_order_index'),
    ]

    operations = [
        migrations.CreateModel(
            name='KeyAlertConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(db_index=True, max_length=100, unique=True)),
                ('min_value', models.FloatField(blank=True, null=True)),
                ('max_value', models.FloatField(blank=True, null=True)),
                ('color_max', models.CharField(blank=True, default='#ff4444', max_length=20)),
                ('color_min', models.CharField(blank=True, default='#ff8800', max_length=20)),
                ('alert_types', models.JSONField(blank=True, default=dict)),
                ('CreationDateTime', models.FloatField(blank=True, db_index=True, null=True, verbose_name='زمان ساخت')),
                ('LastUpdate', models.FloatField(blank=True, max_length=50, null=True, verbose_name='آخرین آپدیت')),
            ],
        ),
    ]
