# Generated by Django 4.2.7 on 2026-01-28 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PLC_Monitoring', '0012_keyalertconfig'),
    ]

    operations = [
        # Step 1: Convert float columns to timestamp using PostgreSQL's to_timestamp
        migrations.RunSQL(
            sql="""
                -- Convert PLC table
                ALTER TABLE "PLC_Monitoring_plc" 
                ALTER COLUMN "CreationDateTime" TYPE timestamp with time zone 
                USING CASE 
                    WHEN "CreationDateTime" IS NOT NULL 
                    THEN to_timestamp("CreationDateTime") 
                    ELSE NULL 
                END;
                
                ALTER TABLE "PLC_Monitoring_plc" 
                ALTER COLUMN "LastUpdate" TYPE timestamp with time zone 
                USING CASE 
                    WHEN "LastUpdate" IS NOT NULL 
                    THEN to_timestamp("LastUpdate") 
                    ELSE NULL 
                END;
                
                -- Convert Rolls table
                ALTER TABLE "PLC_Monitoring_rolls" 
                ALTER COLUMN "CreationDateTime" TYPE timestamp with time zone 
                USING CASE 
                    WHEN "CreationDateTime" IS NOT NULL 
                    THEN to_timestamp("CreationDateTime") 
                    ELSE NULL 
                END;
                
                ALTER TABLE "PLC_Monitoring_rolls" 
                ALTER COLUMN "LastUpdate" TYPE timestamp with time zone 
                USING CASE 
                    WHEN "LastUpdate" IS NOT NULL 
                    THEN to_timestamp("LastUpdate") 
                    ELSE NULL 
                END;
                
                -- Convert Roll_Breaks table
                ALTER TABLE "PLC_Monitoring_roll_breaks" 
                ALTER COLUMN "CreationDateTime" TYPE timestamp with time zone 
                USING CASE 
                    WHEN "CreationDateTime" IS NOT NULL 
                    THEN to_timestamp("CreationDateTime") 
                    ELSE NULL 
                END;
                
                ALTER TABLE "PLC_Monitoring_roll_breaks" 
                ALTER COLUMN "LastUpdate" TYPE timestamp with time zone 
                USING CASE 
                    WHEN "LastUpdate" IS NOT NULL 
                    THEN to_timestamp("LastUpdate") 
                    ELSE NULL 
                END;
                
                -- Convert PLC_Logs table
                ALTER TABLE "PLC_Monitoring_plc_logs" 
                ALTER COLUMN "CreationDateTime" TYPE timestamp with time zone 
                USING CASE 
                    WHEN "CreationDateTime" IS NOT NULL 
                    THEN to_timestamp("CreationDateTime") 
                    ELSE NULL 
                END;
                
                ALTER TABLE "PLC_Monitoring_plc_logs" 
                ALTER COLUMN "LastUpdate" TYPE timestamp with time zone 
                USING CASE 
                    WHEN "LastUpdate" IS NOT NULL 
                    THEN to_timestamp("LastUpdate") 
                    ELSE NULL 
                END;
                
                -- Convert PLC_Keys table
                ALTER TABLE "PLC_Monitoring_plc_keys" 
                ALTER COLUMN "CreationDateTime" TYPE timestamp with time zone 
                USING CASE 
                    WHEN "CreationDateTime" IS NOT NULL 
                    THEN to_timestamp("CreationDateTime") 
                    ELSE NULL 
                END;
                
                ALTER TABLE "PLC_Monitoring_plc_keys" 
                ALTER COLUMN "LastUpdate" TYPE timestamp with time zone 
                USING CASE 
                    WHEN "LastUpdate" IS NOT NULL 
                    THEN to_timestamp("LastUpdate") 
                    ELSE NULL 
                END;
                
                -- Convert ChartExcludedKeys table
                ALTER TABLE "PLC_Monitoring_chartexcludedkeys" 
                ALTER COLUMN "CreationDateTime" TYPE timestamp with time zone 
                USING CASE 
                    WHEN "CreationDateTime" IS NOT NULL 
                    THEN to_timestamp("CreationDateTime") 
                    ELSE NULL 
                END;
                
                -- Convert KeyAlertConfig table
                ALTER TABLE "PLC_Monitoring_keyalertconfig" 
                ALTER COLUMN "CreationDateTime" TYPE timestamp with time zone 
                USING CASE 
                    WHEN "CreationDateTime" IS NOT NULL 
                    THEN to_timestamp("CreationDateTime") 
                    ELSE NULL 
                END;
                
                ALTER TABLE "PLC_Monitoring_keyalertconfig" 
                ALTER COLUMN "LastUpdate" TYPE timestamp with time zone 
                USING CASE 
                    WHEN "LastUpdate" IS NOT NULL 
                    THEN to_timestamp("LastUpdate") 
                    ELSE NULL 
                END;
            """,
            reverse_sql="""
                -- Reverse: Convert back to double precision
                ALTER TABLE "PLC_Monitoring_plc" 
                ALTER COLUMN "CreationDateTime" TYPE double precision 
                USING CASE 
                    WHEN "CreationDateTime" IS NOT NULL 
                    THEN EXTRACT(EPOCH FROM "CreationDateTime") 
                    ELSE NULL 
                END;
                
                ALTER TABLE "PLC_Monitoring_plc" 
                ALTER COLUMN "LastUpdate" TYPE double precision 
                USING CASE 
                    WHEN "LastUpdate" IS NOT NULL 
                    THEN EXTRACT(EPOCH FROM "LastUpdate") 
                    ELSE NULL 
                END;
                
                ALTER TABLE "PLC_Monitoring_rolls" 
                ALTER COLUMN "CreationDateTime" TYPE double precision 
                USING CASE 
                    WHEN "CreationDateTime" IS NOT NULL 
                    THEN EXTRACT(EPOCH FROM "CreationDateTime") 
                    ELSE NULL 
                END;
                
                ALTER TABLE "PLC_Monitoring_rolls" 
                ALTER COLUMN "LastUpdate" TYPE double precision 
                USING CASE 
                    WHEN "LastUpdate" IS NOT NULL 
                    THEN EXTRACT(EPOCH FROM "LastUpdate") 
                    ELSE NULL 
                END;
                
                ALTER TABLE "PLC_Monitoring_roll_breaks" 
                ALTER COLUMN "CreationDateTime" TYPE double precision 
                USING CASE 
                    WHEN "CreationDateTime" IS NOT NULL 
                    THEN EXTRACT(EPOCH FROM "CreationDateTime") 
                    ELSE NULL 
                END;
                
                ALTER TABLE "PLC_Monitoring_roll_breaks" 
                ALTER COLUMN "LastUpdate" TYPE double precision 
                USING CASE 
                    WHEN "LastUpdate" IS NOT NULL 
                    THEN EXTRACT(EPOCH FROM "LastUpdate") 
                    ELSE NULL 
                END;
                
                ALTER TABLE "PLC_Monitoring_plc_logs" 
                ALTER COLUMN "CreationDateTime" TYPE double precision 
                USING CASE 
                    WHEN "CreationDateTime" IS NOT NULL 
                    THEN EXTRACT(EPOCH FROM "CreationDateTime") 
                    ELSE NULL 
                END;
                
                ALTER TABLE "PLC_Monitoring_plc_logs" 
                ALTER COLUMN "LastUpdate" TYPE double precision 
                USING CASE 
                    WHEN "LastUpdate" IS NOT NULL 
                    THEN EXTRACT(EPOCH FROM "LastUpdate") 
                    ELSE NULL 
                END;
                
                ALTER TABLE "PLC_Monitoring_plc_keys" 
                ALTER COLUMN "CreationDateTime" TYPE double precision 
                USING CASE 
                    WHEN "CreationDateTime" IS NOT NULL 
                    THEN EXTRACT(EPOCH FROM "CreationDateTime") 
                    ELSE NULL 
                END;
                
                ALTER TABLE "PLC_Monitoring_plc_keys" 
                ALTER COLUMN "LastUpdate" TYPE double precision 
                USING CASE 
                    WHEN "LastUpdate" IS NOT NULL 
                    THEN EXTRACT(EPOCH FROM "LastUpdate") 
                    ELSE NULL 
                END;
                
                ALTER TABLE "PLC_Monitoring_chartexcludedkeys" 
                ALTER COLUMN "CreationDateTime" TYPE double precision 
                USING CASE 
                    WHEN "CreationDateTime" IS NOT NULL 
                    THEN EXTRACT(EPOCH FROM "CreationDateTime") 
                    ELSE NULL 
                END;
                
                ALTER TABLE "PLC_Monitoring_keyalertconfig" 
                ALTER COLUMN "CreationDateTime" TYPE double precision 
                USING CASE 
                    WHEN "CreationDateTime" IS NOT NULL 
                    THEN EXTRACT(EPOCH FROM "CreationDateTime") 
                    ELSE NULL 
                END;
                
                ALTER TABLE "PLC_Monitoring_keyalertconfig" 
                ALTER COLUMN "LastUpdate" TYPE double precision 
                USING CASE 
                    WHEN "LastUpdate" IS NOT NULL 
                    THEN EXTRACT(EPOCH FROM "LastUpdate") 
                    ELSE NULL 
                END;
            """
        ),
        # Step 2: Update Django's model state to reflect the change
        migrations.AlterField(
            model_name='chartexcludedkeys',
            name='CreationDateTime',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='زمان ساخت'),
        ),
        migrations.AlterField(
            model_name='keyalertconfig',
            name='CreationDateTime',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='زمان ساخت'),
        ),
        migrations.AlterField(
            model_name='keyalertconfig',
            name='LastUpdate',
            field=models.DateTimeField(blank=True, null=True, verbose_name='آخرین آپدیت'),
        ),
        migrations.AlterField(
            model_name='plc',
            name='CreationDateTime',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='زمان ساخت'),
        ),
        migrations.AlterField(
            model_name='plc',
            name='LastUpdate',
            field=models.DateTimeField(blank=True, null=True, verbose_name='آخرین آپدیت'),
        ),
        migrations.AlterField(
            model_name='plc_keys',
            name='CreationDateTime',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='زمان ساخت'),
        ),
        migrations.AlterField(
            model_name='plc_keys',
            name='LastUpdate',
            field=models.DateTimeField(blank=True, null=True, verbose_name='آخرین آپدیت'),
        ),
        migrations.AlterField(
            model_name='plc_logs',
            name='CreationDateTime',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='زمان ساخت'),
        ),
        migrations.AlterField(
            model_name='plc_logs',
            name='LastUpdate',
            field=models.DateTimeField(blank=True, null=True, verbose_name='آخرین آپدیت'),
        ),
        migrations.AlterField(
            model_name='roll_breaks',
            name='CreationDateTime',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='زمان ساخت'),
        ),
        migrations.AlterField(
            model_name='roll_breaks',
            name='LastUpdate',
            field=models.DateTimeField(blank=True, null=True, verbose_name='آخرین آپدیت'),
        ),
        migrations.AlterField(
            model_name='rolls',
            name='CreationDateTime',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='زمان ساخت'),
        ),
        migrations.AlterField(
            model_name='rolls',
            name='LastUpdate',
            field=models.DateTimeField(blank=True, null=True, verbose_name='آخرین آپدیت'),
        ),
    ]
