# Generated by Django 4.2.7 on 2026-05-03 06:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Customer', '0001_initial'),
        ('Supplier', '0001_initial'),
        ('Material', '0001_initial'),
        ('Warehouse', '0001_initial'),
        ('Trucks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(blank=True, choices=[(1, 'Registered'), (2, 'LoadingUnloading'), (3, 'LoadedUnloaded'), (4, 'Office'), (5, 'Delivered'), (6, 'Cancelled')], default=1, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('receive_date', models.CharField(blank=True, max_length=50, null=True, verbose_name='تاریخ دریافت')),
                ('weight1_time', models.CharField(blank=True, max_length=50, null=True, verbose_name='زمان وزن 1')),
                ('weight2_time', models.CharField(blank=True, max_length=50, null=True, verbose_name='زمان وزن 2')),
                ('exit_time', models.CharField(blank=True, max_length=50, null=True, verbose_name='زمان خروج')),
                ('shipment_type', models.IntegerField(choices=[(1, 'Incoming'), (2, 'Outgoing')], default=1)),
                ('weight1', models.CharField(blank=True, max_length=10, null=True, verbose_name='وزن 1')),
                ('unload_location', models.CharField(blank=True, max_length=255, null=True, verbose_name='مکان خروجی')),
                ('quantity', models.CharField(blank=True, max_length=50, null=True, verbose_name='مقدار')),
                ('quality', models.CharField(blank=True, max_length=255, null=True, verbose_name='کیفیت')),
                ('penalty', models.CharField(blank=True, max_length=255, null=True, verbose_name='پیکان')),
                ('weight2', models.CharField(blank=True, max_length=10, null=True, verbose_name='وزن 2')),
                ('net_weight', models.CharField(blank=True, max_length=10, null=True)),
                ('list_of_reels', models.TextField(blank=True, null=True)),
                ('profile_name', models.CharField(blank=True, max_length=255, null=True)),
                ('width', models.CharField(blank=True, max_length=50, null=True)),
                ('sales_id', models.CharField(blank=True, max_length=50, null=True)),
                ('price_per_kg', models.CharField(blank=True, max_length=255, null=True, verbose_name='قیمت برای کیلوگرم')),
                ('total_price', models.CharField(blank=True, max_length=255, null=True)),
                ('extra_cost', models.CharField(blank=True, max_length=255, null=True)),
                ('vat', models.CharField(blank=True, max_length=50, null=True)),
                ('invoice_status', models.CharField(blank=True, choices=[('NA', 'NA'), ('Sent', 'Sent'), ('Received', 'Received')], max_length=255, null=True)),
                ('payment_status', models.CharField(blank=True, choices=[('Terms', 'Terms'), ('Paid', 'Paid')], max_length=255, null=True)),
                ('document_info', models.TextField(blank=True, null=True)),
                ('comments', models.TextField(blank=True, null=True)),
                ('cancellation_reason', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('Is_Deleted', models.BooleanField(default=False)),
                ('CreationDateTime', models.FloatField(blank=True, max_length=50, null=True, verbose_name='زمان ساخت')),
                ('LastUpdate', models.FloatField(blank=True, max_length=50, null=True, verbose_name='آخرین آپدیت')),
                ('Customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='shipment_customer', to='Customer.customer', verbose_name='مشتری')),
                ('Supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='shipment_supplier', to='Supplier.supplier', verbose_name='تامین کننده')),
                ('Truck', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Trucks.truck')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='shipment_location', to='Warehouse.warehouse', verbose_name='مکان')),
                ('material', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='shipment_material_name', to='Material.material', verbose_name='نام ماده')),
            ],
        ),
    ]
