# Generated by Django 4.2.7 on 2025-08-30 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VersionControl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(default='0', max_length=6, verbose_name='نسخه نرم افزار')),
                ('CreationDateTime', models.CharField(blank=True, default=1756536403.2686691, max_length=50, null=True, verbose_name='زمان ساخت')),
                ('LastUpdate', models.CharField(blank=True, max_length=50, null=True, verbose_name='آخرین آپدیت')),
            ],
        ),
    ]
