# Generated by Django 4.2.7 on 2025-09-21 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_alter_versioncontrol_creationdatetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='versioncontrol',
            name='CreationDateTime',
            field=models.CharField(blank=True, default=1758445587.6138413, max_length=50, null=True, verbose_name='زمان ساخت'),
        ),
    ]
