# Generated by Django 4.2.7 on 2026-04-09 08:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChartExcludedKeys',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(db_index=True, max_length=100, unique=True)),
                ('CreationDateTime', models.DateTimeField(auto_now_add=True, db_index=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='KeyAlertConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(db_index=True, max_length=100, unique=True)),
                ('min_value', models.FloatField(blank=True, null=True)),
                ('min_value_2', models.FloatField(blank=True, null=True)),
                ('max_value', models.FloatField(blank=True, null=True)),
                ('max_value_2', models.FloatField(blank=True, null=True)),
                ('color_max', models.CharField(blank=True, default='#ff8800', max_length=20)),
                ('color_max_2', models.CharField(blank=True, default='#ff4444', max_length=20)),
                ('color_min', models.CharField(blank=True, default='#ff4444', max_length=20)),
                ('color_min_2', models.CharField(blank=True, default='#ffaa00', max_length=20)),
                ('alert_types', models.JSONField(blank=True, default=dict)),
                ('CreationDateTime', models.DateTimeField(auto_now_add=True, db_index=True, null=True)),
                ('LastUpdate', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PLC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(db_index=True, max_length=50, unique=True)),
                ('ip_address', models.CharField(blank=True, max_length=100, null=True)),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('setting', models.JSONField(blank=True, null=True)),
                ('Is_Known', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True, null=True)),
                ('CreationDateTime', models.DateTimeField(auto_now_add=True, db_index=True, null=True)),
                ('LastUpdate', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PLC_Keys',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('fa_name', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('key', models.CharField(db_index=True, max_length=100)),
                ('value', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('order_index', models.IntegerField(db_index=True, default=0)),
                ('description', models.TextField(blank=True, null=True)),
                ('live_background', models.BooleanField(blank=True, default=False)),
                ('value_max', models.FloatField(blank=True, default=100)),
                ('CreationDateTime', models.DateTimeField(auto_now_add=True, db_index=True, null=True)),
                ('LastUpdate', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Rolls',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plc_setting', models.JSONField(blank=True, null=True)),
                ('roll_number', models.IntegerField(blank=True, db_index=True, null=True)),
                ('Printed_length', models.IntegerField(blank=True, default=0, null=True)),
                ('Paper_breaks', models.IntegerField(blank=True, default=0, null=True)),
                ('Is_Deleted', models.BooleanField(blank=True, default=False, null=True)),
                ('CreationDateTime', models.DateTimeField(auto_now_add=True, db_index=True, null=True)),
                ('LastUpdate', models.DateTimeField(auto_now=True, null=True)),
                ('plc', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rolls', to='PLC_Monitoring.plc')),
            ],
        ),
        migrations.CreateModel(
            name='Roll_Breaks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('break_reason', models.CharField(blank=True, max_length=250, null=True)),
                ('CreationDateTime', models.DateTimeField(auto_now_add=True, db_index=True, null=True)),
                ('LastUpdate', models.DateTimeField(auto_now=True, null=True)),
                ('roll', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='roll_breaks', to='PLC_Monitoring.rolls')),
            ],
        ),
        migrations.CreateModel(
            name='PLC_Logs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_running', models.BooleanField(blank=True, default=False, null=True)),
                ('data', models.TextField()),
                ('json_data', models.JSONField(blank=True, null=True)),
                ('CreationDateTime', models.DateTimeField(auto_now_add=True, db_index=True, null=True)),
                ('LastUpdate', models.DateTimeField(auto_now=True, null=True)),
                ('plc', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='plc_logs', to='PLC_Monitoring.plc')),
                ('roll', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='roll_logs', to='PLC_Monitoring.rolls')),
            ],
        ),
        migrations.AddIndex(
            model_name='plc',
            index=models.Index(fields=['device_id'], name='PLC_Monitor_device__32d612_idx'),
        ),
        migrations.AddIndex(
            model_name='plc',
            index=models.Index(fields=['CreationDateTime'], name='PLC_Monitor_Creatio_df5b33_idx'),
        ),
    ]
