# Generated by Django 4.2.7 on 2026-05-03 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('Is_Deleted', models.BooleanField(default=False)),
                ('CreationDateTime', models.FloatField(blank=True, max_length=50, null=True, verbose_name='زمان ساخت')),
                ('LastUpdate', models.FloatField(blank=True, max_length=50, null=True, verbose_name='آخرین آپدیت')),
            ],
        ),
    ]
