# Generated by Django 4.2.7 on 2025-11-05 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('save_logs', '0004_alter_device_creationdatetime_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='AI_Target',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='Is_AI',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='device_sensor',
            name='AI_Target',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='device_sensor',
            name='Is_AI',
            field=models.BooleanField(default=False),
        ),
    ]
