# Generated by Django 4.2.7 on 2025-12-08 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Visions', '0008_alter_organizingvisiondata_forklift_driver_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizingvisiondata',
            name='enter',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='ورود'),
        ),
        migrations.AddField(
            model_name='organizingvisiondata',
            name='exit',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='خروج'),
        ),
    ]
