# Generated by Django 4.2.7 on 2025-12-08 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Visions', '0010_organizingvisiondata_enter_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizingvisiondata',
            name='time_text',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='زمان'),
        ),
    ]
