# Generated by Django 4.2.7 on 2025-12-10 08:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Warehouse', '0005_alter_warehousevision_vision_and_more'),
        ('Visions', '0013_alter_organizingvisiondata_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizingvisiondata',
            name='destenation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='organizing_vision_data_destenation', to='Warehouse.warehouse', verbose_name='انبار مقصد'),
        ),
        migrations.AlterField(
            model_name='organizingvisiondata',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='organizing_vision_data_location', to='Warehouse.warehouse', verbose_name='انبار'),
        ),
    ]
