# Generated by Django 4.2.7 on 2026-01-21 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Visions', '0016_organizingvisiondata_mismatch_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizingvisiondata',
            name='comment',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
