# Generated by Django 4.2.7 on 2025-12-13 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DatabaseConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rotation_mode', models.CharField(choices=[('yearly', 'سالانه'), ('monthly', 'ماهانه'), ('manual', 'دستی')], default='yearly', max_length=20, verbose_name='حالت چرخش')),
                ('max_size_mb', models.IntegerField(default=500, verbose_name='حداکثر حجم (مگابایت)')),
                ('max_records', models.IntegerField(default=1000000, verbose_name='حداکثر رکورد')),
                ('auto_rotate', models.BooleanField(default=True, verbose_name='چرخش خودکار')),
                ('keep_logs_count', models.IntegerField(default=100, verbose_name='تعداد لاگ نگهداری برای هر سنسور')),
                ('CreationDateTime', models.FloatField(blank=True, null=True, verbose_name='زمان ساخت')),
                ('LastUpdate', models.FloatField(blank=True, null=True, verbose_name='آخرین آپدیت')),
            ],
            options={
                'verbose_name': 'تنظیمات دیتابیس',
                'verbose_name_plural': 'تنظیمات دیتابیس',
            },
        ),
        migrations.CreateModel(
            name='DatabaseRegistry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='نام دیتابیس')),
                ('file_path', models.CharField(max_length=500, verbose_name='مسیر فایل')),
                ('year', models.IntegerField(db_index=True, verbose_name='سال')),
                ('month', models.IntegerField(blank=True, null=True, verbose_name='ماه')),
                ('status', models.CharField(choices=[('active', 'فعال'), ('archived', 'آرشیو'), ('corrupted', 'خراب')], default='active', max_length=20, verbose_name='وضعیت')),
                ('is_current', models.BooleanField(default=False, verbose_name='دیتابیس فعلی')),
                ('size_mb', models.FloatField(default=0, verbose_name='حجم (مگابایت)')),
                ('records_count', models.IntegerField(default=0, verbose_name='تعداد رکورد')),
                ('CreationDateTime', models.FloatField(blank=True, null=True, verbose_name='زمان ساخت')),
                ('LastUpdate', models.FloatField(blank=True, null=True, verbose_name='آخرین آپدیت')),
            ],
            options={
                'verbose_name': 'دیتابیس',
                'verbose_name_plural': 'دیتابیس\u200cها',
                'ordering': ['-year', '-month'],
            },
        ),
        migrations.CreateModel(
            name='UserDatabaseSelection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(max_length=100, unique=True, verbose_name='کلید نشست')),
                ('selected_databases', models.JSONField(default=list, verbose_name='دیتابیس\u200cهای انتخاب شده')),
                ('view_mode', models.CharField(default='current', max_length=20, verbose_name='حالت نمایش')),
                ('CreationDateTime', models.FloatField(blank=True, null=True, verbose_name='زمان ساخت')),
                ('LastUpdate', models.FloatField(blank=True, null=True, verbose_name='آخرین آپدیت')),
            ],
            options={
                'verbose_name': 'انتخاب دیتابیس کاربر',
                'verbose_name_plural': 'انتخاب\u200cهای دیتابیس کاربران',
            },
        ),
    ]
