# Generated by Django 4.2.7 on 2025-12-13 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DatabaseGuardian', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='databaseregistry',
            options={'ordering': ['-year', '-month', '-day'], 'verbose_name': 'دیتابیس', 'verbose_name_plural': 'دیتابیس\u200cها'},
        ),
        migrations.AddField(
            model_name='databaseregistry',
            name='day',
            field=models.IntegerField(blank=True, null=True, verbose_name='روز'),
        ),
    ]
