# Generated by Django 4.2.7 on 2025-12-14 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DatabaseGuardian', '0002_alter_databaseregistry_options_databaseregistry_day'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalDatabaseSelection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_databases', models.JSONField(default=list, verbose_name='دیتابیس\u200cهای انتخاب شده')),
                ('view_mode', models.CharField(default='current', max_length=20, verbose_name='حالت نمایش')),
                ('CreationDateTime', models.FloatField(blank=True, null=True, verbose_name='زمان ساخت')),
                ('LastUpdate', models.FloatField(blank=True, null=True, verbose_name='آخرین آپدیت')),
            ],
            options={
                'verbose_name': 'انتخاب دیتابیس',
                'verbose_name_plural': 'انتخاب دیتابیس',
            },
        ),
        migrations.DeleteModel(
            name='UserDatabaseSelection',
        ),
        migrations.AlterField(
            model_name='databaseconfig',
            name='keep_logs_count',
            field=models.IntegerField(default=0, verbose_name='تعداد لاگ نگهداری برای هر سنسور'),
        ),
    ]
