# Generated by Django 4.2.7 on 2025-12-09 10:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Unit', '0001_initial'),
        ('Shipments', '0003_alter_shipment_exit_time_alter_shipment_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='shipment_unit', to='Unit.unit', verbose_name='واحد'),
        ),
    ]
