# Generated by Django 4.2.7 on 2025-12-08 06:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Warehouse', '0005_alter_warehousevision_vision_and_more'),
        ('Forklift', '0003_alter_unload_quantity'),
        ('Shipments', '0003_alter_shipment_exit_time_alter_shipment_quantity_and_more'),
        ('Visions', '0005_alter_vision_warehouse'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizingVisionData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Type', models.IntegerField(blank=True, choices=[(1, 'تخلیه'), (2, 'بارگیری'), (3, 'جابجایی'), (4, 'صرفا تردد ( ورود )'), (5, 'صرفا تردد ( خروج )')], default=1, null=True)),
                ('count', models.IntegerField(blank=True, default=0, null=True, verbose_name='تعداد')),
                ('start_time', models.FloatField(blank=True, max_length=50, null=True, verbose_name='زمان شروع')),
                ('end_time', models.FloatField(blank=True, max_length=50, null=True, verbose_name='زمان پایان')),
                ('quantity', models.CharField(blank=True, max_length=255, null=True, verbose_name='مقدار')),
                ('quality', models.CharField(blank=True, max_length=255, null=True, verbose_name='کیفیت')),
                ('Is_Deleted', models.BooleanField(default=False)),
                ('CreationDateTime', models.FloatField(blank=True, max_length=50, null=True, verbose_name='زمان ساخت')),
                ('LastUpdate', models.FloatField(blank=True, max_length=50, null=True, verbose_name='آخرین آپدیت')),
                ('forklift_driver_name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Forklift.forklift_drivers')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='Warehouse.warehouse')),
                ('shipment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='Shipments.shipment')),
            ],
        ),
    ]
