# Generated by Django 4.2.7 on 2025-12-08 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Visions', '0009_organizingvisiondata_enter_organizingvisiondata_exit'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizingvisiondata',
            name='enter_count',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='تعداد ورود'),
        ),
        migrations.AddField(
            model_name='organizingvisiondata',
            name='exit_count',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='تعداد خروج'),
        ),
        migrations.AddField(
            model_name='organizingvisiondata',
            name='move_count',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='تعداد جابجایی'),
        ),
    ]
