# Generated by Django 4.2.7 on 2025-12-08 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Visions', '0012_organizingvisiondata_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizingvisiondata',
            name='Type',
            field=models.IntegerField(blank=True, choices=[(1, 'تخلیه'), (2, 'بارگیری'), (3, 'جابجایی'), (4, 'ورود'), (5, 'خروج')], default=1, null=True),
        ),
    ]
