# Generated by Django 4.2.7 on 2025-12-10 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Visions', '0015_organizingvisiondata_is_checked'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizingvisiondata',
            name='mismatch_count',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='تعداد غیر مطابقت'),
        ),
    ]
