# Generated by Django 4.2.7 on 2025-11-29 12:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Supplier', '0001_initial'),
        ('Customer', '0001_initial'),
        ('Material', '0002_materialtype_description'),
        ('Warehouse', '0005_alter_warehousevision_vision_and_more'),
        ('Shipments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='Customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='shipment_customer', to='Customer.customer', verbose_name='مشتری'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='Supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='shipment_supplier', to='Supplier.supplier', verbose_name='تامین کننده'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='invoice_status',
            field=models.CharField(blank=True, choices=[('NA', 'NA'), ('Sent', 'Sent'), ('Received', 'Received')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='list_of_reels',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='shipment_location', to='Warehouse.warehouse', verbose_name='مکان'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='material',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='shipment_material_name', to='Material.material', verbose_name='نام ماده'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='net_weight',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='payment_status',
            field=models.CharField(blank=True, choices=[('Terms', 'Terms'), ('Paid', 'Paid')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='penalty',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='پیکان'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='profile_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='quality',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='کیفیت'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='quantity',
            field=models.IntegerField(blank=True, null=True, verbose_name='مقدار'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='sales_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='unit',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='واحد'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='unload_location',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='مکان خروجی'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='vat',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='weight1',
            field=models.IntegerField(blank=True, null=True, verbose_name='وزن 1'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='weight2',
            field=models.IntegerField(blank=True, null=True, verbose_name='وزن 2'),
        ),
    ]
