# Generated by Django 4.2.7 on 2025-12-02 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shipments', '0002_alter_shipment_customer_alter_shipment_supplier_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='exit_time',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='زمان خروج'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='quantity',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='مقدار'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='receive_date',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='تاریخ دریافت'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='sales_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='status',
            field=models.IntegerField(blank=True, choices=[(1, 'Registered'), (2, 'LoadingUnloading'), (3, 'LoadedUnloaded'), (4, 'Office'), (5, 'Delivered'), (6, 'Cancelled')], default=1, null=True),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='vat',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='weight1',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='وزن 1'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='weight1_time',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='زمان وزن 1'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='weight2',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='وزن 2'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='weight2_time',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='زمان وزن 2'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='width',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
