# Generated by Django 4.2.7 on 2026-01-06 09:53

from django.db import migrations

from django.db import migrations

class Migration(migrations.Migration):
    dependencies = [
        ('PLC_Monitoring', '0011_plc_keys_order_index'),  # Your last valid migration before 0012
    ]

    operations = [
        # Convert float timestamps to datetime using SQL
        migrations.RunSQL(
            # Forward: Convert Unix timestamps to datetime format
            sql="""
                UPDATE PLC_Monitoring_plc 
                SET CreationDateTime = datetime(CreationDateTime, 'unixepoch'),
                    LastUpdate = datetime(LastUpdate, 'unixepoch')
                WHERE CreationDateTime IS NOT NULL;
                
                UPDATE PLC_Monitoring_rolls 
                SET CreationDateTime = datetime(CreationDateTime, 'unixepoch'),
                    LastUpdate = datetime(LastUpdate, 'unixepoch')
                WHERE CreationDateTime IS NOT NULL;
                
                UPDATE PLC_Monitoring_roll_breaks 
                SET CreationDateTime = datetime(CreationDateTime, 'unixepoch'),
                    LastUpdate = datetime(LastUpdate, 'unixepoch')
                WHERE CreationDateTime IS NOT NULL;
                
                UPDATE PLC_Monitoring_plc_logs 
                SET CreationDateTime = datetime(CreationDateTime, 'unixepoch'),
                    LastUpdate = datetime(LastUpdate, 'unixepoch')
                WHERE CreationDateTime IS NOT NULL;
                
                UPDATE PLC_Monitoring_plc_keys 
                SET CreationDateTime = datetime(CreationDateTime, 'unixepoch'),
                    LastUpdate = datetime(LastUpdate, 'unixepoch')
                WHERE CreationDateTime IS NOT NULL;
                
                UPDATE PLC_Monitoring_chartexcludedkeys 
                SET CreationDateTime = datetime(CreationDateTime, 'unixepoch')
                WHERE CreationDateTime IS NOT NULL;
            """,
            # Reverse: Convert back to Unix timestamp
            reverse_sql="""
                UPDATE PLC_Monitoring_plc 
                SET CreationDateTime = strftime('%s', CreationDateTime),
                    LastUpdate = strftime('%s', LastUpdate);
                    
                UPDATE PLC_Monitoring_rolls 
                SET CreationDateTime = strftime('%s', CreationDateTime),
                    LastUpdate = strftime('%s', LastUpdate);
                    
                UPDATE PLC_Monitoring_roll_breaks 
                SET CreationDateTime = strftime('%s', CreationDateTime),
                    LastUpdate = strftime('%s', LastUpdate);
                    
                UPDATE PLC_Monitoring_plc_logs 
                SET CreationDateTime = strftime('%s', CreationDateTime),
                    LastUpdate = strftime('%s', LastUpdate);
                    
                UPDATE PLC_Monitoring_plc_keys 
                SET CreationDateTime = strftime('%s', CreationDateTime),
                    LastUpdate = strftime('%s', LastUpdate);
                    
                UPDATE PLC_Monitoring_chartexcludedkeys 
                SET CreationDateTime = strftime('%s', CreationDateTime);
            """
        ),
    ]
