# Generated by Django 4.2.7 on 2026-01-06 09:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('PLC_Monitoring', '0012_convert_to_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chartexcludedkeys',
            name='CreationDateTime',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='زمان ساخت'),
        ),
        migrations.AlterField(
            model_name='plc',
            name='CreationDateTime',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='زمان ساخت'),
        ),
        migrations.AlterField(
            model_name='plc',
            name='LastUpdate',
            field=models.DateTimeField(auto_now=True, default=django.utils.timezone.now, verbose_name='آخرین آپدیت'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='plc_keys',
            name='CreationDateTime',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='زمان ساخت'),
        ),
        migrations.AlterField(
            model_name='plc_keys',
            name='LastUpdate',
            field=models.DateTimeField(auto_now=True, default=django.utils.timezone.now, verbose_name='آخرین آپدیت'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='plc_logs',
            name='CreationDateTime',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='زمان ساخت'),
        ),
        migrations.AlterField(
            model_name='plc_logs',
            name='LastUpdate',
            field=models.DateTimeField(auto_now=True, default=django.utils.timezone.now, verbose_name='آخرین آپدیت'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='roll_breaks',
            name='CreationDateTime',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='زمان ساخت'),
        ),
        migrations.AlterField(
            model_name='roll_breaks',
            name='LastUpdate',
            field=models.DateTimeField(auto_now=True, default=django.utils.timezone.now, verbose_name='آخرین آپدیت'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='rolls',
            name='CreationDateTime',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='زمان ساخت'),
        ),
        migrations.AlterField(
            model_name='rolls',
            name='LastUpdate',
            field=models.DateTimeField(auto_now=True, default=django.utils.timezone.now, verbose_name='آخرین آپدیت'),
            preserve_default=False,
        ),
    ]
