# Generated by Django 4.2.7 on 2025-11-26 09:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Visions', '0002_vision_vision_id_visiondata'),
        ('Warehouse', '0004_remove_warehouse_vision_warehousevision'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warehousevision',
            name='vision',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vision_warehouse', to='Visions.vision'),
        ),
        migrations.AlterField(
            model_name='warehousevision',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warehouse_vision', to='Warehouse.warehouse'),
        ),
    ]
