# Generated by Django 4.2.7 on 2026-05-05 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProductsMachine', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productsmachine',
            name='api',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
