# Generated by Django 4.2.7 on 2026-05-26 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PLC_Monitoring', '0016_tcp_connection'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tcp_connection',
            name='LastUpdate',
        ),
        migrations.AddField(
            model_name='tcp_connection',
            name='ClientLastUpdate',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tcp_connection',
            name='ServerLastUpdate',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
