# Generated by Django 4.2.7 on 2026-01-05 12:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Shipments', '0004_alter_shipment_unit'),
        ('Unit', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='shipment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='unit_shipment', to='Shipments.shipment', verbose_name='مرسوله'),
        ),
    ]
