# Generated by Django 4.2.7 on 2026-06-20 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_versioncontrol_desc_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='versioncontrol',
            name='CreationDateTime',
            field=models.CharField(blank=True, default=1781953278.1972775, max_length=50, null=True, verbose_name='زمان ساخت'),
        ),
    ]
