# Generated by Django 5.2.5 on 2025-12-28 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='versioncontrol',
            name='CreationDateTime',
            field=models.CharField(blank=True, default=1766907533.4020357, max_length=50, null=True, verbose_name='زمان ساخت'),
        ),
    ]
