# Generated by Django 5.2.5 on 2025-12-28 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_versioncontrol_creationdatetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='versioncontrol',
            name='CreationDateTime',
            field=models.CharField(blank=True, default=1766908605.589307, max_length=50, null=True, verbose_name='زمان ساخت'),
        ),
    ]
