# Generated by Django 4.2.7 on 2025-11-22 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Visions', '0001_initial'),
        ('Warehouse', '0002_warehouse_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehouse',
            name='vision',
            field=models.ManyToManyField(blank=True, null=True, to='Visions.vision'),
        ),
    ]
