# Generated by Django 5.2.5 on 2025-12-27 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PLC_Monitoring', '0006_plc_keys_fa_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='plc_logs',
            name='is_running',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='plc_logs',
            name='roll_number',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
    ]
