# Generated by Django 4.2.7 on 2025-12-31 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PLC_Monitoring', '0010_chartexcludedkeys'),
    ]

    operations = [
        migrations.AddField(
            model_name='plc_keys',
            name='order_index',
            field=models.IntegerField(db_index=True, default=0),
        ),
    ]
