# Generated by Django 4.2.7

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PLC_Monitoring', '0012_keyalertconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='keyalertconfig',
            name='min_value_2',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='keyalertconfig',
            name='max_value_2',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='keyalertconfig',
            name='color_max_2',
            field=models.CharField(blank=True, default='#ff8800', max_length=20),
        ),
        migrations.AddField(
            model_name='keyalertconfig',
            name='color_min_2',
            field=models.CharField(blank=True, default='#ffaa00', max_length=20),
        ),
    ]
