# Generated by Django 4.2.7

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PLC_Monitoring', '0013_keyalertconfig_min_value_2_max_value_2'),
    ]

    operations = [
        migrations.AddField(
            model_name='plc_keys',
            name='live_background',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='plc_keys',
            name='value_max',
            field=models.FloatField(blank=True, default=100),
        ),
    ]
