# Generated by Django 4.2.7 on 2026-02-15 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PLC_Monitoring', '0014_plc_keys_live_background_value_max'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keyalertconfig',
            name='color_min',
            field=models.CharField(blank=True, default='#ff4444', max_length=20),
        ),
    ]
