# Generated by Django 4.2.7 on 2025-09-09 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('save_logs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='CreationDateTime',
            field=models.CharField(blank=True, default=1757404756.773376, max_length=50, null=True, verbose_name='زمان ساخت'),
        ),
        migrations.AlterField(
            model_name='device_sensor',
            name='CreationDateTime',
            field=models.CharField(blank=True, default=1757404756.773376, max_length=50, null=True, verbose_name='زمان ساخت'),
        ),
        migrations.AlterField(
            model_name='sensorlogs',
            name='CreationDateTime',
            field=models.CharField(blank=True, default=1757404756.773376, max_length=50, null=True, verbose_name='زمان ساخت'),
        ),
    ]
