# Generated by Django 4.2.7 on 2026-07-16 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_versioncontrol_desc_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TCP_CONNECTION',
        ),
        migrations.AlterField(
            model_name='versioncontrol',
            name='CreationDateTime',
            field=models.CharField(blank=True, default=1784185376.9496171, max_length=50, null=True, verbose_name='زمان ساخت'),
        ),
    ]
