# Generated by Django 4.2.7 on 2025-12-17 12:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PLC_Monitoring', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PLC_Keys',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(db_index=True, max_length=100)),
                ('value', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('CreationDateTime', models.FloatField(blank=True, db_index=True, null=True, verbose_name='زمان ساخت')),
                ('LastUpdate', models.FloatField(blank=True, max_length=50, null=True, verbose_name='آخرین آپدیت')),
                ('plc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plc_keys', to='PLC_Monitoring.plc')),
            ],
        ),
    ]
