# Generated by Django 4.2.7 on 2025-12-20 06:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PLC_Monitoring', '0003_remove_plc_logs_plc_alter_plc_keys_plc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plc_keys',
            name='plc',
        ),
        migrations.AddField(
            model_name='plc_logs',
            name='json_data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='plc_logs',
            name='plc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='plc_logs', to='PLC_Monitoring.plc'),
        ),
    ]
