# Generated by Django 5.2.5 on 2025-12-28 07:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PLC_Monitoring', '0007_plc_logs_is_running_plc_logs_roll_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rolls',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plc_setting', models.JSONField(blank=True, null=True)),
                ('roll_number', models.IntegerField(blank=True, db_index=True, null=True)),
                ('Printed_length', models.IntegerField(blank=True, default=0, null=True)),
                ('Paper_breaks', models.IntegerField(blank=True, default=0, null=True)),
                ('Is_Deleted', models.BooleanField(blank=True, default=False, null=True)),
                ('CreationDateTime', models.FloatField(blank=True, db_index=True, null=True, verbose_name='زمان ساخت')),
                ('LastUpdate', models.FloatField(blank=True, max_length=50, null=True, verbose_name='آخرین آپدیت')),
            ],
        ),
        migrations.RemoveField(
            model_name='plc_logs',
            name='roll_number',
        ),
        migrations.CreateModel(
            name='Roll_Breaks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('break_reason', models.CharField(blank=True, max_length=250, null=True)),
                ('CreationDateTime', models.FloatField(blank=True, db_index=True, null=True, verbose_name='زمان ساخت')),
                ('LastUpdate', models.FloatField(blank=True, max_length=50, null=True, verbose_name='آخرین آپدیت')),
                ('roll', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='roll_breaks', to='PLC_Monitoring.rolls')),
            ],
        ),
        migrations.AddField(
            model_name='plc_logs',
            name='roll',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='roll_logs', to='PLC_Monitoring.rolls'),
        ),
    ]
