# Generated by Django 4.2.7 on 2026-05-30 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('save_logs', '0005_device_ai_target_device_is_ai_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='AI_Target',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='CreationDateTime',
            field=models.FloatField(blank=True, db_index=True, max_length=50, null=True, verbose_name='زمان ساخت'),
        ),
        migrations.AlterField(
            model_name='device',
            name='Is_AI',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='device',
            name='Is_Known',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='device',
            name='LastUpdate',
            field=models.FloatField(blank=True, db_index=True, max_length=50, null=True, verbose_name='آخرین آپدیت'),
        ),
        migrations.AlterField(
            model_name='device',
            name='description',
            field=models.TextField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='device_id',
            field=models.CharField(db_index=True, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='ip_address',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='location',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='name',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='device_sensor',
            name='AI_Target',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='device_sensor',
            name='CreationDateTime',
            field=models.FloatField(blank=True, db_index=True, max_length=50, null=True, verbose_name='زمان ساخت'),
        ),
        migrations.AlterField(
            model_name='device_sensor',
            name='Is_AI',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='device_sensor',
            name='LastUpdate',
            field=models.FloatField(blank=True, db_index=True, max_length=50, null=True, verbose_name='آخرین آپدیت'),
        ),
        migrations.AlterField(
            model_name='device_sensor',
            name='description',
            field=models.TextField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='device_sensor',
            name='sensor_type',
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='sensorlogs',
            name='CreationDateTime',
            field=models.FloatField(blank=True, db_index=True, null=True, verbose_name='زمان ساخت'),
        ),
        migrations.AlterField(
            model_name='sensorlogs',
            name='LastUpdate',
            field=models.FloatField(blank=True, db_index=True, max_length=50, null=True, verbose_name='آخرین آپدیت'),
        ),
        migrations.AlterField(
            model_name='sensorlogs',
            name='data',
            field=models.TextField(db_index=True),
        ),
    ]
