# Generated by Django 4.2.7 on 2026-07-16 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_visitorlog_alter_versioncontrol_creationdatetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='versioncontrol',
            name='CreationDateTime',
            field=models.CharField(blank=True, default=1784183584.9818041, max_length=50, null=True, verbose_name='زمان ساخت'),
        ),
    ]
